### ISSUE TITLE
Semantic validation

### ISSUE THREAD

**Issue by bittremieux** [MS-Quality-Hub/pymzqc#40]
Verify that all semantic checks listed in the specification document are implemented. See [mzQC/#51](https://github.com/HUPO-PSI/mzQC/issues/51).

**Comment by mwalzer** [comment]
fixed with commits prior to [37c4243](https://github.com/MS-Quality-Hub/pymzqc/commit/37c4243bee30036c6e7c80ce36b5b0e6c10e319d)
