### ISSUE TITLE
mzQC file merging

### ISSUE THREAD

**Issue by bittremieux** [MS-Quality-Hub/pymzqc#41]
Add functionality to merge multiple mzQC files.

To resolve conflicts (e.g. different contact name, CV versions, ...), for simplicity, at first make an arbitrary decision among the input.

**Comment by mwalzer** [comment]
I've added a beta version in the accessories, should be available on commandline with `mzqc-filemerger`. We'll test with the broccoli-data from the manuscript.

**Comment by mwalzer** [comment]
https://pymzqc.readthedocs.io/en/v1.0.0rc3/accessories.html#filemerger, I'll close this when v1.0.0rc3 is merged into main
