### ISSUE TITLE
DOC: using the validator locally

### ISSUE THREAD

**Issue by cbielow** [MS-Quality-Hub/pymzqc#44]
maybe add a small example to https://pymzqc.readthedocs.io/en/v1.0.0rc1_b/examples.html
on how to run the validator locally.
Minimal version
```
from mzqc import MZQCFile as qc
from mzqc import SemanticCheck as sc

file = open("/path/to/your.mzQC", "r")

qcobj = qc.JsonSerialisable.FromJson(file)

sobj = sc.SemanticCheck(qcobj)
sobj.validate( qc.JsonSerialisable().ToJson(qcobj) )
```
which may need some adoption in the upcoming API??

Also, how to grab the latest PSI-MS CV for validation would be appreciated.

**Comment by mwalzer** [comment]
https://pymzqc.readthedocs.io/en/v1.0.0rc3/accessories.html, I'll close the issue when v1.0.0rc3 merges into main
