### ISSUE TITLE
Weird indentation

### ISSUE THREAD

**Issue by bittremieux** [MS-Quality-Hub/pymzqc#51]
When setting `readability` of `JsonSerialisable.ToJson`, the indentation of the produced mzQC file is not entirely correct. E.g.:
```
{"mzQC": 
{
    "creationDate": "2024-08-21T13:43:14Z",
    "version": "1.0.0",
                "runQualities": [
        {
```

- `"mzqc"` should be on a new line and indented once.
- `"runQualities"` is indented too much.

I'd also maybe suggest only 2 spaces per indentation level instead of 4, to have somewhat more compact (yet still legible) documents.

**Comment by mwalzer** [comment]
#51 and #53 are actually connected. Funny business with indents came from incompletely removing empty optional elements.
Sanitising happens only if using `ToJson/FromJson`.
I guess I will prepare a dedicated documentation page for top-level functionality and entry/exit points? Not sure yet how to best structure the docs.

**Comment by mwalzer** [comment]
This is the defaults for ToJson. Sensible?
```
        readability : int, optional
            The indentation level, by default 0 (=no indentation, 
            1=minor indentation on MZQC objects, >1 heavy indentation for max. 
            human readability)
```
(minor indentation is 2 spaces, heavy is 4 spaces and some more newlines if I remember correctly)

**Comment by bittremieux** [comment]
Yes, those defaults seem fine.
