### ISSUE TITLE
unit of QualityMetric should be a CvParameter

### ISSUE THREAD

**Issue by bittremieux** [MS-Quality-Hub/pymzqc#52]
[Instead of a string](https://github.com/MS-Quality-Hub/pymzqc/blob/main/mzqc/MZQCFile.py#L361).

**Comment by mwalzer** [comment]
> Although actually assigning a `CvParameter` serializes correctly

I think that is actually the automagic of the `JsonSerialisable` class_mapper and so on that adapts correctly during runtime. Initially, everything defaults to strings (or numbers) because of json.
Since it's a hen-egg situation I'd tend to fix-in-documentation.
